### ISSUE TITLE
Make it so all operations have a creator_uid

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha-mobile-app#218]
The creator_uid is intended to correspond to the person who is signing the transaction, all operations should have one

**Comment by osdiab** [comment]
Or rather, we should make it so that all operations have creator_id, and ban the use of the term “uid”.

That said, I wonder how much the consistency matters right now, given that a lot of the operations probably won’t directly correspond to blockhain transactions in the long run. For instance, as of now create_member is usable by any unauthenticated user for free, which is a recipe for the blockhain getting ddos’d with unverified account signups.

**Comment by rahulgi** [comment]
All operations do have a creator_uid. The operation you're looking at is CreateMember, and request_invite_from_member_id is an optional field that indicates that the member is joining via an invite sent by someone else. Agreed we do want to be consistent in using `member_id` instead of `uid`.

**Comment by markulrich** [comment]
Ah I see! Thanks
