### ISSUE TITLE
Make CodePush changes take effect immediately on app launch

### ISSUE THREAD

**Issue by tinaroh** [rahafoundation/raha-mobile-app#293]

**Comment by rahulgi** [comment]
Ah, I didn't realize - from the appcenter UI we can specify whether a Codepush release is mandatory. This will make the update get installed immediately. I'm in favor of doing this instead of installing every codepush update immediately, as it is closer to best-practices. Thoughts?

https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#plugin-usage (look for "mandatory").

**Comment by tinaroh** [comment]
That sounds good to me, in the future I'm sure we'll have more updates that are not critical to be applied on app start. I'm a fan of being a good citizen and not requiring the user to download more than is necessary :)
